CREATE TABLE branding_scheduled_icon (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    cron_expression VARCHAR(128) NOT NULL,
    icon LONGBLOB NOT NULL,
    icon_content_type VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
